In [1]:
from numpy import array
from numpy import diag
from numpy import dot
from scipy.linalg import svd

In [3]:
A=array([[1,2,3],[4,5,6],[7,8,9]])
print(A)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
U,s,VT=svd(A)

In [7]:
print(U)

[[-0.21483724  0.88723069  0.40824829]
 [-0.52058739  0.24964395 -0.81649658]
 [-0.82633754 -0.38794278  0.40824829]]


In [9]:
print(s)

[1.68481034e+01 1.06836951e+00 4.41842475e-16]


In [11]:
print(VT)

[[-0.47967118 -0.57236779 -0.66506441]
 [-0.77669099 -0.07568647  0.62531805]
 [-0.40824829  0.81649658 -0.40824829]]


In [13]:
Sigma=diag(s)

In [15]:
print(Sigma)

[[1.68481034e+01 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 1.06836951e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 4.41842475e-16]]


In [17]:
B=U.dot(Sigma.dot(VT))
print(B)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
